name: Create-Variables
on: push

jobs:
  job1:
    name: Creating and passing variables
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SecureHats JsonTo-Variable
        id: step1
        uses: SecureHats/JsonTo-Variable@v0.1.0
        with:
          filePath: 'package.json'
          arraySeparator: ','
          outputs: $true

  job2:
      needs: [job1]
      name: Reading previous variables
      runs-on: ubuntu-latest

      steps:
      - name: Print output variable
        run: |
          echo "having dinner with ${{ needs.job1.result }} in ${{ needs.job1.result }}"
