name: Create-Variables
on: push

jobs:
  job1:
    name: Creating and passing variables
    runs-on: ubuntu-latest

    steps:
      - name: Get values from the package.json
        id: packageJson
        uses: RadovanPelka/github-action-json@main
        with:
          path: "package.json" # default value

      - run: echo "name - ${{ steps.packageJson.outputs.name }}"
      - run: echo "version - ${{ steps.packageJson.outputs.version }}"
      - run: echo "author - ${{ steps.packageJson.outputs.author }}"
